export enum RolePermissions {
  VIEW_ISSUES = 'VIEW_ISSUES',
  VIEW_MEMBERS = 'VIEW_MEMBERS',
  VIEW_ROLES = 'VIEW_ROLES',
  VIEW_INVITES = 'VIEW_INVITES',

  CREATE_ISSUE = 'CREATE_ISSUE',
  CREATE_INVITE = 'CREATE_INVITE',
  CREATE_ROLE = 'CREATE_ROLE',

  DELETE_ISSUE = 'DELETE_ISSUE',
  DELETE_INVITE = 'DELETE_INVITE',
  DELETE_ROLE = 'DELETE_ROLE',
  DELETE_MEMBER = 'DELETE_MEMBER',

  EDIT_ISSUE = 'EDIT_ISSUE',
  EDIT_MEMBER = 'EDIT_MEMBER',
  EDIT_ROLE = 'EDIT_ROLE',
  EDIT_SETTINGS = 'EDIT_SETTINGS',

  BAN_MEMBER = 'BAN_MEMBER',
}